### root route
GET http://localhost:5000/

### all access content
GET http://localhost:5000/api/test/all/

### Signup user
POST http://localhost:5000/api/auth/signup/
Content-Type: application/json

{
    "username": "user",
    "email": "user@email.com",
    "password": "user123"
}

### Signin user
POST http://localhost:5000/api/auth/signin/
Content-Type: application/json

{
    "email": "user@email.com",
    "password": "user123"
}

### Accessing user content without authentication
GET http://localhost:5000/api/test/user/

### Accessing user content with user privilleges
GET http://localhost:5000/api/test/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1MTdmODNkZTllYmRkOTgwNDliNiIsImlhdCI6MTY0NzU5NTkwOCwiZXhwIjoxNjQ3NjgyMzA4fQ.EpLTjnX81BDuhJj5WXbgt16kPU0V60Q2C97Ic6zFaII

### Accessing moderator content with user privilleges
GET http://localhost:5000/api/test/moderator/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1MTdmODNkZTllYmRkOTgwNDliNiIsImlhdCI6MTY0NzU5NTkwOCwiZXhwIjoxNjQ3NjgyMzA4fQ.EpLTjnX81BDuhJj5WXbgt16kPU0V60Q2C97Ic6zFaII

### Accessing admin content with user privilleges
GET http://localhost:5000/api/test/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1MTdmODNkZTllYmRkOTgwNDliNiIsImlhdCI6MTY0NzU5NTkwOCwiZXhwIjoxNjQ3NjgyMzA4fQ.EpLTjnX81BDuhJj5WXbgt16kPU0V60Q2C97Ic6zFaII

### Signup moderator
POST http://localhost:5000/api/auth/signup/
Content-Type: application/json

{
    "username": "moderator",
    "email": "moderator@email.com",
    "password": "moderator123",
    "roles": ["moderator"]
}

### Signin moderator
POST http://localhost:5000/api/auth/signin/
Content-Type: application/json

{
    "email": "moderator@email.com",
    "password": "moderator123"
}

### Accessing moderator content without authentication
GET http://localhost:5000/api/test/moderator/

### Accessing user content with moderator privilleges
GET http://localhost:5000/api/test/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1MjgxMzIyOGM3ODA3NTE4N2I1NCIsImlhdCI6MTY0NzU5NjY3NywiZXhwIjoxNjQ3NjgzMDc3fQ.CjLmbZdpOwPWBi5Cpztzvm7lYwm_-jZGpUPcPCiL4qg

### Accessing moderator content with moderator privilleges
GET http://localhost:5000/api/test/moderator/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1MjgxMzIyOGM3ODA3NTE4N2I1NCIsImlhdCI6MTY0NzU5NjY3NywiZXhwIjoxNjQ3NjgzMDc3fQ.CjLmbZdpOwPWBi5Cpztzvm7lYwm_-jZGpUPcPCiL4qg

### Accessing admin content with moderator privilleges
GET http://localhost:5000/api/test/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1MjgxMzIyOGM3ODA3NTE4N2I1NCIsImlhdCI6MTY0NzU5NjY3NywiZXhwIjoxNjQ3NjgzMDc3fQ.CjLmbZdpOwPWBi5Cpztzvm7lYwm_-jZGpUPcPCiL4qg


### Signup admin
POST http://localhost:5000/api/auth/signup/
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@email.com",
    "password": "admin123",
    "roles": ["admin"]
}

### Signin admin
POST http://localhost:5000/api/auth/signin/
Content-Type: application/json

{
    "email": "admin@email.com",
    "password": "admin123"
}

### Accessing admin content without authentication
GET http://localhost:5000/api/test/admin/

### Accessing user content with admin privilleges
GET http://localhost:5000/api/test/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1NjVmYjgyYjgwZjBiMWE4MTk4OCIsImlhdCI6MTY0NzU5NzE1NiwiZXhwIjoxNjQ3NjgzNTU2fQ.OP0WTYe0nHbdOuK33Y6WgInb0PQ4EBPKRCGFX7rHjUY

### Accessing moderator content with admin privilleges
GET http://localhost:5000/api/test/moderator/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1NjVmYjgyYjgwZjBiMWE4MTk4OCIsImlhdCI6MTY0NzU5NzE1NiwiZXhwIjoxNjQ3NjgzNTU2fQ.OP0WTYe0nHbdOuK33Y6WgInb0PQ4EBPKRCGFX7rHjUY

### Accessing admin content with admin privilleges
GET http://localhost:5000/api/test/admin/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzQ1NjVmYjgyYjgwZjBiMWE4MTk4OCIsImlhdCI6MTY0NzU5NzE1NiwiZXhwIjoxNjQ3NjgzNTU2fQ.OP0WTYe0nHbdOuK33Y6WgInb0PQ4EBPKRCGFX7rHjUY